### ISSUE TITLE
Not working error code

### ISSUE THREAD

**Issue by ShadowWeagle** [Red-Killer/lb-musicapp#3]
CrBrowserMain/ false (@lb-musicapp/ui/index.html:129)
MainThrd/ ^1SCRIPT ERROR: @lb-musicapp/client.lua:96: No such export PlayUrlPos in resource xsound^7
MainThrd/ ^1SCRIPT ERROR: @lb-musicapp/client.lua:101: No such export soundExists in resource xsound^7

This is probably me being daft and installed something wrong but how do I fix this?

**Comment by Red-Killer** [comment]
do you have xSound?

**Comment by ShadowWeagle** [comment]
I do yes.

**Comment by Red-Killer** [comment]
How is the resource called in your resources folder?

**Comment by ShadowWeagle** [comment]
Just changed it from xsound-master to xsound and am testing that currently

**Comment by ShadowWeagle** [comment]
Got it sorted out, thank you!

**Comment by Red-Killer** [comment]
Okay nice.
